tests/test_note: add mock for note_id
This fixes the following test failures
	[...]
	FAILED tests/test_note.py::test_ok - TypeError: write_to_db() missing 1 requi...
	FAILED tests/test_note.py::test_num_fields_equals_model_ok - TypeError: write...
	FAILED tests/test_note.py::test_num_fields_less_than_model_raises - TypeError...
	FAILED tests/test_note.py::test_num_fields_more_than_model_raises - TypeError...
	FAILED tests/test_note.py::test_warns_on_invalid_html_tags - TypeError: write...
	FAILED tests/test_note.py::test_suppress_warnings - TypeError: write_to_db() ...
	[...]